name: Project Idea Proposal
description: Propose a new coding project for the Codeunia community!
title: '[PROJECT IDEA]: Your Creative Project Title'
labels: ['idea', 'new-idea']
assignees: [] # Can be assigned by leaders later
body:
  - type: markdown
    attributes:
      value: |
        🚀 Thanks for taking the time to propose a new project idea for Codeunia! Please fill out the following details as thoroughly as possible.

  - type: input
    id: project-name
    attributes:
      label: Project Name
      description: What do you want to call your project?
      placeholder: e.g., Community Dashboard, Smart Todo App
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement / Inspiration
      description: What problem does this project solve? What inspired you to think of this?
      placeholder: Describe the need or the idea that sparked this project.
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution / Features
      description: Briefly describe how your project will work and its core features.
      placeholder: What will it do? What will it look like?
    validations:
      required: true

  - type: dropdown
    id: primary-tech
    attributes:
      label: Primary Technologies/Skills
      description: What main technologies, languages, or skills do you envision this project using?
      multiple: true
      options:
        - Python
        - JavaScript (Frontend)
        - JavaScript (Backend/Node.js)
        - HTML/CSS
        - React
        - Angular
        - Vue.js
        - Java
        - C++
        - C#
        - Go
        - Rust
        - Database (SQL/NoSQL)
        - Machine Learning/AI
        - Data Science
        - Mobile Development (Android/iOS)
        - Cloud (AWS/GCP/Azure)
        - IoT
        - Game Development
        - Other (please specify in 'Additional Notes')
    validations:
      required: true

  - type: dropdown
    id: difficulty
    attributes:
      label: Estimated Difficulty Level
      description: How challenging do you think this project will be for a student?
      options:
        - Beginner-Friendly (Great for first-time contributors)
        - Intermediate (Requires some prior experience)
        - Advanced (Complex, suitable for experienced developers)
    validations:
      required: true

  - type: textarea
    id: potential-impact
    attributes:
      label: Potential Impact / Learning Outcomes
      description: What kind of impact could this project have? What skills might contributors learn?
      placeholder: e.g., Improve community engagement, learn full-stack development, gain experience with ML models.
    validations:
      required: false

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes or Resources
      description: Any other information, diagrams, links, or specific requirements?
      placeholder: Feel free to add anything else relevant!
    validations:
      required: false

  - type: checkboxes
    id: interested-in-leading
    attributes:
      label: Your Role
      options:
        - label: I am interested in potentially leading this project.
        - label: I am interested in contributing to this project.
